eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  