server:
  port: 9008
spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/topPlastique
    driverClassName: org.postgresql.Driver
    password: 123456
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
Authentication:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: AuthSecretKey